// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEF23AacVuB0OqQPAX4CV0gQNXRoqzwoo',
    appId: '1:739308254979:web:4ad98bacbda0a36ea99b36',
    messagingSenderId: '739308254979',
    projectId: 'weather-e98bc',
    authDomain: 'weather-e98bc.firebaseapp.com',
    storageBucket: 'weather-e98bc.firebasestorage.app',
    measurementId: 'G-6X8CMV8H02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPftm0xwGdQqw7AmGhPPOw2QTLkzu0F_0',
    appId: '1:739308254979:android:6de64a146e57b041a99b36',
    messagingSenderId: '739308254979',
    projectId: 'weather-e98bc',
    storageBucket: 'weather-e98bc.firebasestorage.app',
  );
}
